# Generated by Django 5.0 on 2025-07-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
