# Generated by Django 5.0 on 2025-07-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_person_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='person',
            field=models.CharField(max_length=100),
        ),
    ]
