# Generated by Django 5.0 on 2025-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('salaries', 'Salaries'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('equipment', 'Equipment'), ('travel', 'Travel'), ('food', 'Food & Entertainment'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
