# Generated by Django 5.0 on 2025-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_remove_expense_description_expense_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('digital_wallet', 'Digital Wallet'), ('other', 'Other')], default='bank_transfer', max_length=20),
        ),
    ]
